website/models.py
from . import db
# from flask_login import UserMixin #para manejo de usuarios
from sqlalchemy.sql import func

from datetime import datetime
import uuid
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin



def generate_uuid():
    return str(uuid.uuid4())


# Admin Model
class Admin(db.Model):
    __tablename__ = 'admins'

    id = db.Column(db.Integer, primary_key=True ) 
    email = db.Column(db.String(255),  nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

# User Model
class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True) #!!convertir este id en secuencial(el primero 1 el segundo 2...)
    email = db.Column(db.String(255), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    name = db.Column(db.String(255), nullable=False)
    has_logged_in = db.Column(db.Boolean, default=False, nullable=False) #!!poner true para cuando se logeen por primera vez 
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

# Services Model
class Service(db.Model):
    __tablename__ = 'services'

    id = db.Column(db.String(36), primary_key=True, default=generate_uuid)
    name = db.Column(db.String(255), nullable=False)
    category = db.Column(db.String(255), nullable=False)
    cost = db.Column(db.Float, nullable=False)
    price = db.Column(db.Float, nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


# Appointment Model
class Appointment(db.Model):
    __tablename__ = 'appointments'

    id = db.Column(db.String(36), primary_key=True, default=generate_uuid)
    date = db.Column(db.Date, nullable=False)
    hour = db.Column(db.Time, nullable=False)
    user_id = db.Column(db.String(36), db.ForeignKey('users.id'), nullable=False)
    service_id = db.Column(db.String(36), db.ForeignKey('services.id'), nullable=False)
    tip = db.Column(db.Float, nullable=True, default=0.0)
    name = db.Column(db.String(255), nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    user = db.relationship('User', backref=db.backref('appointments', lazy=True))
    service = db.relationship('Service', backref=db.backref('appointments', lazy=True))

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    
    app.config['SECRET_KEY'] = 'THIS IS A SECRET KEY. DO NOT SHARE. PLEASE CHANGE.'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'

    # LoginManager is needed for our application 
    # to be able to log in and out users
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from .models import User

    @login_manager.user_loader
    def load_user(user_id):
        # pass
        # # since the user_id is just the primary key of our user table, use it in the query for the user
        return User.query.get(int(user_id))

    # link db with the app
    db.init_app(app)

    from .views import views
    from .auth import auth
    from .install import install
    from .services import services
    from .users import users
    from .appointments import appointments

# to put a prefix (in this case non prefix) to every route
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(install, url_prefix='/')
    app.register_blueprint(services, url_prefix='/')
    app.register_blueprint(users, url_prefix='/')
    app.register_blueprint(appointments, url_prefix='/')




    # incluir las demas tablas ademas de Admin
    from .models import Admin, User, Appointment, Service

    create_database(app)


    return app


def create_database(app):
    # check if the db is already create.
    if not path.exists('website/' + DB_NAME):
        with app.app_context():  # Entra al contexto de la aplicación
            db.create_all()
            print("Created Database!!")

website/auth.py
from flask import Blueprint,  render_template, request, jsonify, url_for, flash, session, redirect
from . import db
from .models import Admin, User
from flask_login import login_user
from flask_login import login_required, current_user
from .users import create_user


#se va a definir los blueprints, son un monton de rutas para poder dividir el codigo
auth = Blueprint('auth', __name__)

    #!! configurar login required


@auth.route('/login',  methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        print("EN EL GET DE LOGIN")
        render_template('login.html')

    if request.method == 'POST':
        print("EN EL POST DE LOGIN")

        email = request.form.get('email')
        password = request.form.get('password')
        
        admin = Admin.query.filter_by(email = email).first()
        user = User.query.filter_by(email = email).first()
        
        if admin:
            if password == user.password:
                print("admin password correct ")
                session['admin'] = True

            else:
                print("Password incorrect")
                flash("Incorrect password", 'danger')

                return "error en login post o admin con mal password"
        elif user:
            print(user.name)
            if password == user.password:
                print("user password correct ")
                session['user'] = True

        else:
            flash("No user", 'danger')
            return ("errorrrrrrr")
        
         # if the above check passes, then we know the user has the right credentials
        login_user(user)
        # login_user(user, remember=remember)

        return redirect(url_for('views.home'))
        

    return render_template('login.html')


@auth.route('/logout')
@login_required
def logout():
    #!! login required ??

    session.clear()
    return redirect(url_for('auth.login') )


@auth.route('/signup', methods = ['POST', 'GET'])
def signup():

    if request.method == 'GET':
        render_template('signup.html')
    elif request.method == 'POST':

        name = request.form.get('name')

        email = request.form.get('email')
        password = request.form.get('password')

        print(f"Nombre recibido: {name}")
        print(f"Email recibido: {email}")
        print(f"Password recibido: {password}")

        user = User(name=name, email = email, password=password ) # Crear un nuevo usuario

        try:
            db.session.add(user)
            db.session.commit()  # Guardar cambios

        except Exception as e:
            print("Error")
            db.session.rollback()  # Revertir cambios si hay un error
            return "Error"
        
        print("user created succesfully from signup")
        return redirect(url_for('auth.login'))
        

    # AQUI LEES EL FORM DEL USUARIO Y PONES EL USER EN LA TABLA DE USERS
    return render_template('signup.html')

website/views.py
from flask import Blueprint, render_template, redirect, url_for, request, session
from .models import Admin, User, Service, Appointment
from . import db
from datetime import datetime
from flask_login import login_required, current_user

#!! check flask-wtf

#se va a definir los blueprints, son un monton de rutas para poder dividir el codigo
views = Blueprint('views', __name__)


@views.route('/')
def index():
    admin = Admin.query.all()

    # 1, 0, None
    print("llego aqui")

    # si no hay nada en la db entonces a esa ruta
    if not admin:
        return redirect(url_for('install.finstall'))

    return render_template('index.html')


@views.route('/home' , methods = ['GET'])
@login_required
def home():
    if request.method == 'GET':
        print("EN EL GET DE HOME")
        if 'admin' in session:
            print("es admin")

    access = session.get('admin')
    
    
    return render_template('home.html', current_user=current_user)



@views.route('/settings', methods = ['GET'])
@login_required
def settings():
    if request.method == 'GET':
        print("Settings get")
        if not "admin" in session:
            print("cannot access")
            #!! o mandar a otro lado o modificar el html para user settings
        else:
            print("hello!!")
            return render_template('settings.html')
        

@views.route('/month', methods = ['GET'])
@login_required
def month():
    if request.method == 'GET':
        print('month get')
    return "month"

website/templates/appointments.html
{% extends "base.html" %}{% block title %} appointments list {% endblock %}



{% block content %}

    <H1>This is the view appointments page</H1>

    <button class="btn btn-secondary"> 

        <a href="{{url_for('appointments.create_appointment')}}">Create appointment</a>


    </button>
        
  <table id="data" class="table table-striped">


    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>date</th>
        <th>hour</th>
        <th>user_id</th>
        <th>service_id</th>
        <th>tip</th>
        <th>actions</th>
      </tr>
    </thead>
    <tbody>
      {% for appointment in apointment_list %}
        <tr>
          <td>{{ appointment.id}}</td>
          <td>{{ appointment.date}}</td>
          <td>{{ appointment.hour}}</td>
          <td>{{ appointment.user_id}}</td>
          <td>{{ appointment.service_id}}</td>
          <td>{{ appointment.tip}}</td>

          <td>{{ user.name }}</td>
          <td>
            <ul>
                <li><a href="{{ url_for('users.edit_user', user_id=user.id) }}">Edit</a></li>
                <li><a href="{{url_for('users.delete_user', user_id=user.id)}}">Delete</a></li>
                <li><a href="{{url_for('users.delete_user', user_id=user.id)}}">Admin</a></li>

            </ul>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
    



{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <title>Document</title> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">


    <title>{% block title %}Home{% endblock %}</title>

    <!-- {% block head %}{% endblock %} -->
</head>
<body>
    
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('views.settings') }}">Settings <span class="sr-only">(current)</span></a>


        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('appointments.view_appointments') }}">My appointments <span class="sr-only">(current)</span></a>
        </li>
        

          
        {% if current_user.is_authenticated %}

        <li class="nav-item active">


          <a class="nav-link" href="{{ url_for('auth.logout') }}">logout<span class="sr-only">(current)</span></a>


          
      </li>

        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('auth.logout') }}">Sign-up<span class="sr-only">(current)</span></a>    
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('auth.logout') }}">Login<span class="sr-only">(current)</span></a>
    </li>

        {% endif %}
        

        

        <!-- <li class="nav-item"> -->
          <!-- <a class="nav-link" href="#">Features</a> -->
        <!-- </li> -->
        <!-- <li class="nav-item"> -->
          <!-- <a class="nav-link" href="#">Pricing</a> -->
        <!-- </li> -->
        <!-- <li class="nav-item dropdown"> -->
          <!-- <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> -->
            <!-- Dropdown link -->
          <!-- </a> -->
          <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> -->
            <!-- <a class="dropdown-item" href="#">Action</a> -->
            <!-- <a class="dropdown-item" href="#">Another action</a> -->
            <!-- <a class="dropdown-item" href="#">Something else here</a> -->
          </div>
        </li>
      </ul>
    </div>
  </nav>


    <!-- <ul> -->
        <!-- <li>hola</li> -->
        <!-- <li>adios</li> -->
        <!-- <li>aqui se puede ver como se esta poniendo cuando se llama a Home </li> -->
    <!-- </ul> -->

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>


    <!-- <h2>Aqui algo despues del bloque</h2> -->
    
    
</body>
</html>

website/templates/form_appointment.html
{% extends "base.html" %}{% block title %} form_appointment {% endblock %}



{% block content %}
<h1>This is the form_apppointment page</h1>





<br>
<br>
<br>
<br><br>
hola
{{appointment_id}}


{% if create %}
<form action="/create_appointment" method="POST">



{% else %}

<form action="/edit_appointment/{{appointment_id}}" method="POST">



{% endif %}
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="Name">
    </div>
  </div>




  <div class="form-group">

    <label for="date">Date:</label>
    <input type="date" id="date" name="date" value="" min="" max="" />


    <label for="hour">Choose a time for your meeting:</label>
    <input type="time" id="hour" name="hour" min="" max="" required />
    <small>Office hours are 9am to 6pm</small>



    <label for="tip">Tip</label>
    <input type="number" id="tip" name="tip" step="0.01" min="0" placeholder="0.00">



        
  <div class="form-row">
      <!-- <div class="form-group col-md-6"> -->
        <!-- <label for="inputCity">City</label> -->
        <!-- <input type="text" class="form-control" id="inputCity"> -->
      <!-- </div> -->
    <div class="form-group col-md-4">

        <label for="client">Client</label>
        <select id="category" name="client" class="form-control">
            <option selected>none</option>
            {% for client in clients%} 
            <option> {{client.name}}</option>
            {% endfor %}
        </select>

        <label for="service">Service</label>
        <select id="service" name="service" class="form-control">
            <option selected>none</option>
            {% for service in services%} 
            <option> {{service.name}}</option>
            {% endfor %}
        </select>

    </div>




    </div>

    {% if create %}
      <button type="submit" class="btn btn-primary">Create Appointment</button>

  
    {% else %}
    
      <button type="submit" class="btn btn-primary">Edit Appointment</button>
    

    {% endif %}

  </form>




{% endblock %}

website/templates/form_service.html
{% extends "base.html" %}{% block title %} Create {% endblock %}



{% block content %}
<h1>This is the create page</h1>





<br>
<br>
<br>
<br><br>


{% if create %}
<form action="/create_service" method="POST">



{% else %}

<form action="/edit_service/{{service_id}}" method="POST">



{% endif %}
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="Name">
    </div>
  </div>

    


  <div class="form-group">

    <label for="inputAddress">Price</label>
    <input type="number" id="price" name="price" step="0.01" min="0" placeholder="0.00">


    <label for="inputAddress">Cost</label>
    <input type="number" id="cost" name="cost" step="0.01" min="0" placeholder="0.00">




        
  <div class="form-row">
      <!-- <div class="form-group col-md-6"> -->
        <!-- <label for="inputCity">City</label> -->
        <!-- <input type="text" class="form-control" id="inputCity"> -->
      <!-- </div> -->
    <div class="form-group col-md-4">

        <label for="inputState">Category</label>
        <select id="category" name="category" class="form-control">
          <option selected>Facial</option>
          <option>Corporal</option>
          <option>Certificado</option>
        </select>

        
    </div>




    </div>

    {% if create %}
      <button type="submit" class="btn btn-primary">Create Service</button>

  
    {% else %}
    
      <button type="submit" class="btn btn-primary">Edit Service</button>
    

    {% endif %}

  </form>




{% endblock %}

website/templates/form_user.html
{% extends "base.html" %}{% block title %} Create user {% endblock %}



{% block content %}
<h1>This is the create page user</h1>





<br>
<br>
<br>
<br><br>



{% if create %}

<form action="/create_user" method="POST">
  




{% else %}

<form action="/edit_user/{{user_id}}" method="POST">




{% endif %}


        
    <label for="name">Name:</label>
    <input type="tetx" id="name" name="name" required>

    <label for="email">Correo Electrónico:</label>
    <input type="email" id="email" name="email" required>

    <br><br>
    
    <label for="password">Contraseña:</label>
    <input type="password" id="password" name="password" required>
    
    <br><br>


    {% if create %}
      <button type="submit" class="btn btn-primary">Create User</button>

  
    {% else %}
    
    <button type="submit" class="btn btn-primary">Edit User</button>
    

    {% endif %}

  </form>




{% endblock %}

website/templates/home.html
{% extends "base.html" %}{% block title %} Home {% endblock %}



{% block content %}
<h1>this is home</h1>



{% endblock %}

website/templates/index.html
{% extends "base.html" %}{% block title %} Home {% endblock %}



{% block content %}
<h1>This is the index page</h1>






{% endblock %}

website/templates/install.html
{% extends "base.html" %}{% block title %} INSTALL {% endblock %}



{% block content %}


<h2>Formulario de Registro. SOLO FLASK</h2>
<form action="/install_post" method="POST">
    <label for="name">Nombre:</label>
    <input type="text" id="name" name="name" required>
    <br><br>
    <label for="email">Correo Electrónico:</label>
    <input type="email" id="email" name="email" required>
    <br><br>
    <label for="password">Contraseña:</label>
    <input type="password" id="password" name="password" required>
    <br><br>
    <button type="submit">Registrarse</button>
</form>





{% endblock %}

website/templates/login.html
{% extends "base.html" %}{% block title %} Login {% endblock %}



{% block content %}
<h1>This is the LOGIN page</h1>



<form action="/login" method="POST">

    <label for="email">Correo Electrónico:</label>
    <input type="email" id="email" name="email" required>
    <br><br>
    <label for="password">Contraseña:</label>
    <input type="password" id="password" name="password" required>
    <br><br>
    <button type="submit">Log-In</button>
</form>




{% endblock %}

website/templates/settings.html
{% extends "base.html" %}{% block title %} Settings {% endblock %}



{% block content %}
<h1>This is the Setting page</h1>


<ul>
    <li>
        <a href="{{url_for('views.month')}}">month</a>
    </li>

    <li>
        <a href="{{url_for('services.create_service')}}">Create service</a>
        
    </li>


    <li>
        <a href="{{url_for('services.view_services')}}">View Services</a>

    </li>

    <li>
        <a href="{{url_for('users.view_users')}}">View Users</a>

    </li>

    <li>
        <a href="{{url_for('users.create_user')}}">Create Users</a>

    </li>
    <li>
        <a href="{{url_for('appointments.view_appointments')}}">View Appointments</a>

    </li>
    <li>
        <a href="{{url_for('appointments.create_appointment')}}">Create Appointments</a>

    </li>



</ul>


{% endblock %}

website/templates/signup.html
{% extends "base.html" %}{% block title %} sign-up {% endblock %}



{% block content %}
<h1>This is the sign-up page</h1>

<form action="/signup" method="POST">

    
    <label for="name">Name:</label>
    <input type="tetx" id="name" name="name" required>

    <label for="email">Correo Electrónico:</label>
    <input type="email" id="email" name="email" required>

    <br><br>
    
    <label for="password">Contraseña:</label>
    <input type="password" id="password" name="password" required>
    
    <br><br>
    
    <button type="submit">Sign-up</button>
</form>
{% endblock %}

website/templates/users.html
{% extends "base.html" %}{% block title %} users list {% endblock %}



{% block content %}

    <H1>This is the view users page</H1>

    <button class="btn btn-secondary"> 

        <a href="{{url_for('users.create_user')}}">Create User</a>


    </button>
        
  <table id="data" class="table table-striped">


    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Status</th>
        <th>Next Appoiment</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for user in user_list %}
        <tr>
          <td>{{ user.name }}</td>
          <td>{{ user.email }}</td>
          <td>{{ user.has_logged_in }}</td>
          <td> Next Appoiment</td>
          <td>
            <ul>
                <li><a href="{{ url_for('users.edit_user', user_id=user.id) }}">Edit</a></li>
                <li><a href="{{url_for('users.delete_user', user_id=user.id)}}">Delete</a></li>
                <li><a href="{{url_for('users.delete_user', user_id=user.id)}}">Admin</a></li>

            </ul>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
    



{% endblock %}

website/templates/view_appointments.html
{% extends "base.html" %}{% block title %} appointments list {% endblock %}



{% block content %}

    <H1>This is the view appointments page</H1>

    <button class="btn btn-secondary"> 

        <a href="{{url_for('appointments.create_appointment')}}">Create appointment</a>


    </button>
        
  <table id="data" class="table table-striped">


    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>date</th>
        <th>hour</th>
        <th>user_id</th>
        <th>service_id</th>
        <th>tip</th>
        <th>actions</th>
      </tr>
    </thead>
    <tbody>
      
      {% for appointment in appointment_list %}
        <tr>
          <td>{{ appointment.id}}</td>
          <td>hola</td>
          <td>{{ appointment.date}}</td>
          <td>{{ appointment.hour}}</td>
          <td>{{ appointment.user_id}}</td>
          <td>{{ appointment.service_id}}</td>
          <td>{{ appointment.tip}}</td>

        
          <td>
            <ul>
                <li><a href="{{ url_for('appointments.edit_appointment', appointment_id=appointment.id) }}">Edit</a></li>
                <li><a href="{{url_for('appointments.delete_appointment', appointment_id=appointment.id)}}">Delete</a></li>
                

            </ul>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>




{% endblock %}

website/templates/view_services.html
{% extends "base.html" %}{% block title %} services list {% endblock %}



{% block content %}

    <H1>This is the view services page</H1>


  <table id="data" class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Cost</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for service in services_list %}
        <tr>
          <td>{{ service.name }}</td>
          <td>{{ service.price }}</td>
          <td>{{ service.cost }}</td>
          <td>
            <ul>
                <li><a href="{{ url_for('services.edit_service', service_id=service.id) }}">Edit</a></li>
                <li><a href="{{url_for('services.delete_service', service_id=service.id)}}">Delete</a></li>
            </ul>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}